### PR TITLE
New sign for Uris 108

### PR DESCRIPTION
**Pull request by cappadona**
Using main Uris hours and newly minted friendly URL for LibCal
(/uris-interview).

### CODE REVIEW

**Comment by miniaturekites** [comment]
Hi Nick, when you get a chance, can you generate another staging instance of the sign for Uris 108 for testing?

**Comment by cappadona** [comment]
@miniaturekites Spinning up as I type...

**Comment by miniaturekites** [comment]
https://signage-stg-pr-133.herokuapp.com/ is a mostly blank page (it only says "Cornell University Library Signage"). I tried appending /uris-interview, but that was a 404 page. Do I have the right URL?

**Comment by cappadona** [comment]
@miniaturekites The correct URL for the 108 sign in this review app is:
https://signage-stg-pr-133.herokuapp.com/uris/spaces/interview

The `/uris-interview` route you see mentioned in the opening comment on this issue is referring to a friendly URL (aka alias) on the LibCal side.

My apologies for the confusion.

**Comment by cappadona** [comment]
Thanks @miniaturekites. Does that mean we can proceed or are we waiting on others to chime in?

**Comment by miniaturekites** [comment]
I don't think we're waiting for anyone else for Uris 108, the LibCal space has already been in use for a while. (we are waiting on Olin 104 (#135), the LibCal space still needs to be created)

**Comment by cappadona** [comment]
Great. I'll plan on deploying this to production tomorrow.

**Comment by cappadona** [comment]
Morning Devin...108 sign is now [live in production](http://signage.library.cornell.edu/uris/spaces/interview).

**Comment by miniaturekites** [comment]
The live page looks good, I'm planing to set up the iPad outside of the room tomorrow morning.

**Pull request merged**
