### PR TITLE
Color swap

### PR DESCRIPTION
**Pull request by cappadona**
Let me know what you think. I ended up going with a slightly deeper blue for the time slots to maintain contrast according to WCAG.

#### Original Blue
screenshot_2019-02-14 mann - studyrooms 6

#### New Blue
screenshot_2019-02-14 mann - studyrooms 7

### CODE REVIEW

**Comment by eeh53** [comment]
@cappadona I like the darker blue - definitely easier to see the contrast.

**Comment by cappadona** [comment]
@eeh53 Thanks...deeper blue can be seen in action here:
* [2nd floor study rooms](https://signage-stg-pr-96.herokuapp.com/mann/spaces/studyrooms)
* [Bissett](https://signage-stg-pr-96.herokuapp.com/mann/spaces/bissett)
* [Room 261](https://signage-stg-pr-96.herokuapp.com/mann/spaces/room261)
* [Olin CoLab](https://signage-stg-pr-96.herokuapp.com/olin/spaces/colab)

If you're good to go, will you submit your approval via the review in the upper right of this page?

**Comment by eeh53** [comment]
@cappadona Will do! Just had a weird thing happen with 261 where the reservations/availability didn't load (the page looked blank) until I refreshed the page. Now I can't seem to recreate the issue. Any idea why that would happen? I'm working in Chrome, just fyi.

**Comment by cappadona** [comment]
Thanks you two. @eeh53, Sara had mentioned experiencing something similar yesterday but I haven't run into it thus far nor have I been able to reproduce it.

It's possible it's related to Chrome's aggressive caching, but let's keep our eye out for it. If it does happen again, do you mind just sitting tight and watching it for a bit? The space schedule from LibCal is cached for 2 minutes so when it's fetched again it should be rendered to the screen automatically.

For now I'm going to merge this and deploy to production.

**Pull request merged**
