### PR TITLE
Use newly minted hours for Olin 104

### PR DESCRIPTION
**Pull request by cappadona**
As per Devin's request in #155.

### CODE REVIEW

**Comment by miniaturekites** [comment]
https://signage-stg-pr-156.herokuapp.com/olin/spaces/room104 (double checking the url) looks good!

**Comment by cappadona** [comment]
That's the one. So green light to deploy to production?

**Comment by miniaturekites** [comment]
Yes, thank you!

**Comment by miniaturekites** [comment]
It isn't showing up yet, will it go live as part of a larger process?

**Comment by cappadona** [comment]
Deployment to production is manually triggered and goes through several tests/verifications. That being said, everything passed and the latest version of the sign has been [released into the wild](https://signage.library.cornell.edu/olin/spaces/room104).

**Comment by miniaturekites** [comment]
Looks good, thank you again.

**Comment by cappadona** [comment]
You're very welcome 😃. Have a good one.

**Pull request merged**
