### PR TITLE
Fluid fonts

### PR DESCRIPTION
**Pull request by manolobevia**
Followup to #22...

### CODE REVIEW

**Comment by cappadona** [comment]
Here are a couple camera captures of the TV, attempting to demonstrate the fuzzy red text...

img_3599
img_3600

**Comment by manolobevia** [comment]
## Both
Done with the item marked check.
* [X] Unavailable text is blurry (see screenshots)
* [x] The bg color for the primary component is a bit dark and the insignia is barely visible beneath
* [x] How do you feel about dropping the colons from the headings?
* [x] Remove hardcoded device unavailability 
* [ ] Think it's possible to ensure that the status and item name/count are always on a single line? Looks like it might be tight for phone chargers, so maybe we just go with consistency and render availability status on second line?

**Comment by cappadona** [comment]
Thanks...jumping in now

**Comment by cappadona** [comment]
@manolobevia Will you create an issue for the remaining item on our list when you get a chance?

**Comment by manolobevia** [comment]
RE: Think it's possible to ensure that the status and item name/count are always on a single line? Looks like it might be tight for phone chargers, so maybe we just go with consistency and render availability status on second line?

I tried so many things. If we have the count/device/ status in one line, the type is going to be really small.

**Comment by cappadona** [comment]
@manolobevia Understood. I'm willing to give your suggestion a shot, consistency within equipment type:

> Maybe for laptop we keep all in one line, for phone charges the count, device in one line and status in another, but no consistency.

**Pull request merged**
