### PR TITLE
New sign for building hours & occupancy

### LINKED ISSUE #181: Mann: Hours & Live Occupancy
- [ ] Building hours via LibCal
- [ ] Live occupancy via Sensource SafeSpace

### PR DESCRIPTION
**Pull request by cappadona**
When open, live occupancy data is displayed.

Initial implementation for following libraries:
* Mann
* Olin
* Uris

Route is `/{{libraryName}}/building`

> Resolves #181

Screenshot_2020-09-29 Mann - Hours

Screenshot_2020-09-29 Uris - Hours

Screenshot_2020-09-29 Olin - Hours

### CODE REVIEW

**Comment by cappadona** [comment]
@sew268 @eeh53 You can view the Mann sign on this temp instance:
https://signage-pr-186.herokuapp.com/mann/building

**Review by sew268 — COMMENTED** [review]
This looks amazing!  Will this live on 1 LCD and the 2nd will house the hours at other open locations and the upcoming events?

**Comment by cappadona** [comment]
Thanks @sew268 😃 

The plan for the second sign is to promote upcoming events. See #182 and please feel free to edit/comment with any additional data you want included there.

**Comment by cappadona** [comment]
Deployed to production 🚀

**Pull request merged**
